version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  admin-backend:
    build: ./backend
    restart: unless-stopped
    environment:
      MQTT_HOST: 27.191.2.71
      MQTT_PORT: '5502'
      MQTT_USERNAME: admin
      MQTT_PASSWORD: wjm234.CN
      MOSQUITTO_CONF: /mosquitto/config/mosquitto.conf
      MOSQUITTO_PWFILE: /mosquitto/config/pwfile
      MOSQUITTO_ACLFILE: /mosquitto/config/aclfile
      MQTT_CONTAINER: mqtt-broker
    volumes:
      - ./mosquitto/config:/mosquitto/config
    ports:
      - '4000:4000'

  admin-frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: http://localhost:4000
        VITE_WS_URL: ws://localhost:4000/ws
    restart: unless-stopped
    ports:
      - '3000:80'
    depends_on:
      - admin-backend
